config/routes.rb
# frozen_string_literal: true

Spina::Engine.routes.draw do
  namespace :admin, path: Spina.config.backend_path do
    namespace :journal do
      resources :journals, only: %i[edit update destroy]
      resources :volumes, except: %i[show update] do
        post 'sort/:journal_id' => 'volumes#sort', as: :sort, on: :collection

        member do
          get :view_issues
        end
      end
      resources :issues, except: %i[show] do
        post 'sort/:volume_id' => 'issues#sort', as: :sort, on: :collection

        member do
          get :view_articles
        end
      end
      resources :articles, except: %i[show] do
        post 'sort/:issue_id' => 'articles#sort', as: :sort, on: :collection

        member do
          get :view_authors
        end
      end
      resources :authors, except: %i[show] do
        post 'sort/:article_id' => 'authors#sort', as: :sort, on: :collection

        member do
          get :view_articles
        end
      end

      resources :institutions, except: %i[show] do
        member do
          get :view_affiliations
        end
      end
      resources :licences, except: %i[show]
    end
  end
end

app/models/spina/admin/journal/article.rb
# frozen_string_literal: true

module Spina
  module Admin
    module Journal
      # Record for an individual article.
      #
      # === Validators
      # Presence:: {#number}, {#title}
      # Uniqueness:: {#number} (scope: issue) {status}
      # URI:: {#url}
      #
      # === Scopes
      # sorted_asc:: sorted in order of increasing number
      # sorted_desc:: sorted highest number first
      # visible:: articles that should be visible to the public
      #
      # @see Issue
      # @see Author
      # @see Authorship
      class Article < ApplicationRecord
        include AttrJson::Record
        include AttrJson::NestedAttributes
        include Spina::Partable
        include Spina::TranslatedContent
        # @!attribute [rw] number
        #   @return [Integer] The position of the article within its issue.
        # @!attribute [rw] title
        #   @return [String] The article's title.
        # @!attribute [rw] url
        #   @return [String] An external link to the article.
        # @!attribute [rw] doi
        #   @return [String] A digital object intentifier for the article.
        # @!attribute [rw] issue
        #   @return [Issue] The issue that contains this article.
        belongs_to :issue
        # @!attribute [rw] licence
        #   @return [Licence] the licence under which the article is released
        belongs_to :licence, optional: true

        # @!attribute [rw] authorships
        has_many :authorships, dependent: :destroy
        # @!attribute [rw] affiliations
        #   @return [ActiveRecord::Relation] The authors of the article.
        has_many :affiliations, through: :authorships

        # @!attribute [rw] status
        #   @return [Integer] the current status of the article
        enum status: { published: 0, draft: 1, meta: 2 }

        validates :number, presence: true, uniqueness: { scope: :issue_id }
        validates :title, presence: true
        validates :url, 'spina/admin/journal/uri': true
        validates :status, presence: true

        scope :visible, -> { where(status: %i[published meta]) }
        scope :sorted_asc, -> { includes(:issue).order('spina_admin_journal_issues.number ASC', number: :asc) }
        scope :sorted_desc, -> { includes(:issue).order('spina_admin_journal_issues.number DESC', number: :desc) }

        # Returns true if the article should be visible to end users (i.e. is not a draft).
        def visible?
          published? || meta?
        end
      end
    end
  end
end

app/controllers/spina/admin/journal/application_controller.rb
# frozen_string_literal: true

module Spina
  module Admin
    module Journal
      # Custom controller for journal plugin. Sets the layout and adds a flash type.
      class ApplicationController < AdminController
        helper ::Spina::Engine.routes.url_helpers

        add_flash_types :success

        layout :admin_layout

        before_action :set_locale

        private

        def admin_layout
          'spina/admin/admin'
        end

        def set_locale
          @locale = params[:locale] || I18n.default_locale
        end
      end
    end
  end
end

app/controllers/spina/admin/journal/articles_controller.rb
# frozen_string_literal: true

module Spina
  module Admin
    module Journal
      # Controller for {Article} records.
      class ArticlesController < ApplicationController
        PARTS_PARAMS = [
          :name, :title, :type, :content, :filename, :signed_blob_id, :alt, :attachment_id, :image_id,
          :first_page, :last_page,
          { images_attributes: %i[filename signed_blob_id image_id alt],
            content_attributes: [
              :name, :title,
              { parts_attributes: [
                :name, :title, :type, :content, :filename, :signed_blob_id, :alt, :attachment_id, :image_id,
                { images_attributes: %i[filename signed_blob_id image_id alt] }
              ] }
            ] }
        ].freeze
        CONTENT_PARAMS = Spina.config.locales.inject({}) do |params, locale|
          params.merge("#{locale}_content_attributes": [*PARTS_PARAMS])
        end
        PARAMS = [:issue_id, :licence_id, :title, :url, :doi, :status, { affiliation_ids: [], **CONTENT_PARAMS }].freeze
        PARTS = %w[abstract attachment page_range].freeze

        before_action :set_breadcrumb
        before_action :set_tabs, except: %i[index destroy sort]
        before_action :set_article, only: %i[edit view_authors update destroy]
        before_action :set_parts_attributes, only: %i[new edit]
        before_action :build_parts, only: %i[edit]

        admin_section :journal

        def index
          @articles = Article.sorted_desc
        end

        def new
          @article = Article.new
          build_parts
          add_breadcrumb t('.new')
        end

        def edit; end

        def view_authors
          render layout: false
        end

        def create # rubocop:disable Metrics/AbcSize
          @article = Article.new(article_params)
          sister_articles = Article.where(issue: @article.issue_id)
          @article.number = sister_articles.any? ? sister_articles.sorted_desc.first.number + 1 : 1

          if @article.save
            redirect_to edit_admin_journal_article_path(@article), success: t('.saved')
          else
            flash.now[:alert] = t('.failed')
            render :new, status: :unprocessable_entity
          end
        end

        def update
          if @article.update(article_params)
            redirect_to edit_admin_journal_article_path(@article), success: t('.saved')
          else
            flash.now[:alert] = t('.failed')
            render :edit, status: :unprocessable_entity
          end
        end

        def destroy
          @article.destroy
          respond_to do |format|
            format.html do
              redirect_to admin_journal_articles_path, success: t('.deleted')
            end
          end
        end

        def sort
          params[:ids].each.with_index do |id, index|
            Article.where(id: id).update_all(number: index + 1) # rubocop:disable Rails/SkipsModelValidations
          end
          flash.now[:info] = t('spina.pages.sorting_saved')
          render_flash
        end

        private

        def article_params
          params.require(:article).permit(PARAMS)
        end

        def set_breadcrumb
          add_breadcrumb Article.model_name.human(count: :many), admin_journal_articles_path
        end

        def set_tabs
          @tabs = %w[details authors]
        end

        def set_article
          @article = Article.find(params[:id])
          add_breadcrumb @article.title
        end

        def set_parts_attributes
          @parts_attributes = current_theme.parts.select { |part| PARTS.include? part[:name] }
        end

        def build_parts
          return unless @parts_attributes.is_a? Array

          @parts = @parts_attributes.collect { |part_attributes| @article.part(part_attributes) }
        end
      end
    end
  end
end

app/controllers/spina/admin/journal/authors_controller.rb
# frozen_string_literal: true

module Spina
  module Admin
    module Journal
      # Controller for {Author} records and their corresponding {Affiliation}s.
      class AuthorsController < ApplicationController
        before_action :set_breadcrumb
        before_action :set_tabs, except: %i[index destroy]
        before_action :set_author, only: %i[edit view_articles update destroy]

        admin_section :journal_settings

        def index
          @authors = Author.all
        end

        def new
          @author = Author.new
          @author.affiliations << Affiliation.new(status: :primary)
          add_breadcrumb t('.new')
        end

        def edit; end

        def view_articles
          render layout: false
        end

        def create
          @author = Author.new(modified_params)
          if @author.save
            redirect_to edit_admin_journal_author_path(@author), success: t('.saved')
          else
            flash.now[:alert] = t('.failed')
            render :new, status: :unprocessable_entity
          end
        end

        def update
          if @author.update(modified_params)
            redirect_to edit_admin_journal_author_path(@author), success: t('.saved')
          else
            flash.now[:alert] = t('.failed')
            render :edit, status: :unprocessable_entity
          end
        end

        def destroy
          @author.destroy
          respond_to do |format|
            format.html do
              redirect_to admin_journal_authors_path, success: t('.deleted')
            end
          end
        end

        def sort
          params[:ids].each.with_index do |id, index|
            Authorship.where(id: id).update_all(position: index + 1) # rubocop:disable Rails/SkipsModelValidations
          end
          flash.now[:info] = t('spina.pages.sorting_saved')
          render_flash
        end

        private

        def author_params
          params.require(:author).permit(:primary_affiliation_index, :orcid,
                                         affiliations_attributes: %i[id institution_id first_name
                                                                     surname])
        end

        def modified_params
          primary_affiliation_index = params[:author][:primary_affiliation_index]
          new_params = author_params.except :primary_affiliation_index
          unless new_params[:affiliations_attributes].nil? || primary_affiliation_index.nil?
            new_params[:affiliations_attributes].each_key do |index|
              new_params[:affiliations_attributes][index][:status] = index == primary_affiliation_index ? 'primary' : 'other' # rubocop:disable Layout/LineLength
            end
          end
          new_params
        end

        def set_breadcrumb
          add_breadcrumb Author.model_name.human(count: :many), admin_journal_authors_path
        end

        def set_tabs
          @tabs = %w[details articles]
        end

        def set_author
          @author = Author.find(params[:id])
          add_breadcrumb @author.primary_affiliation.name
        end
      end
    end
  end
end

app/controllers/spina/admin/journal/institutions_controller.rb
# frozen_string_literal: true

module Spina
  module Admin
    module Journal
      # Controller for {Institution} records
      class InstitutionsController < ApplicationController
        before_action :set_breadcrumb
        before_action :set_tabs, except: %i[index destroy]
        before_action :set_institution, only: %i[edit view_affiliations update destroy]

        admin_section :journal_settings

        def index
          @institutions = Institution.all
        end

        def new
          @institution = Institution.new
          add_breadcrumb t('.new')
        end

        def edit; end

        def view_affiliations
          render layout: false
        end

        def create
          @institution = Institution.new(institution_params)

          if @institution.save
            redirect_to edit_admin_journal_institution_path(@institution), success: t('.saved')
          else
            flash.now[:alert] = t('.failed')
            render :new, status: :unprocessable_entity
          end
        end

        def update
          if @institution.update(institution_params)
            redirect_to edit_admin_journal_institution_path(@institution), success: t('.saved')
          else
            flash.now[:alert] = t('.failed')
            render :edit, status: :unprocessable_entity
          end
        end

        def destroy
          @institution.destroy
          respond_to do |format|
            format.html do
              redirect_to admin_journal_institutions_path, success: t('.deleted')
            end
          end
        end

        private

        def institution_params
          params.require(:institution).permit(:name)
        end

        def set_breadcrumb
          add_breadcrumb Institution.model_name.human(count: :many), admin_journal_institutions_path
        end

        def set_tabs
          @tabs = %w[details view_affiliations]
        end

        def set_institution
          @institution = Institution.find(params[:id])
          add_breadcrumb @institution.name
        end
      end
    end
  end
end

app/controllers/spina/admin/journal/issues_controller.rb
# frozen_string_literal: true

module Spina
  module Admin
    module Journal
      # Controller for {Issue} records.
      # TODO: extract methods to helpers to reduce class length
      class IssuesController < ApplicationController
        PARTS_PARAMS = [
          :name, :title, :type, :content, :filename, :signed_blob_id, :alt, :attachment_id, :image_id,
          { images_attributes: %i[filename signed_blob_id image_id alt],
            content_attributes: [
              :name, :title,
              { parts_attributes: [
                :name, :title, :type, :content, :filename, :signed_blob_id, :alt, :attachment_id, :image_id,
                { images_attributes: %i[filename signed_blob_id image_id alt] }
              ] }
            ] }
        ].freeze
        CONTENT_PARAMS = Spina.config.locales.inject({}) do |params, locale|
          params.merge("#{locale}_content_attributes": [*PARTS_PARAMS])
        end
        PARAMS = [:volume_id, :title, :date, { **CONTENT_PARAMS }].freeze
        PARTS = %w[cover_img description attachment].freeze

        before_action :set_breadcrumb
        before_action :set_tabs, except: %i[index destroy sort]
        before_action :set_issue, only: %i[edit view_articles update destroy]
        before_action :set_articles, only: %i[edit view_articles update]
        before_action :set_parts_attributes, only: %i[new edit]
        before_action :build_parts, only: %i[edit]

        admin_section :journal

        def index
          @issues = Issue.sorted_desc
        end

        def new
          @issue = Issue.new
          build_parts
          add_breadcrumb t('.new')
        end

        def edit
          add_breadcrumb t('spina.admin.journal.volumes.volume_number', number: @issue.volume.number),
                         edit_admin_journal_volume_path(@issue.volume)
          add_breadcrumb t('spina.admin.journal.issues.issue_number', number: @issue.number)
        end

        def view_articles
          render layout: false
        end

        def create # rubocop:disable Metrics/AbcSize
          @issue = Issue.new(issue_params)
          sister_issues = Issue.where(volume: @issue.volume_id)
          @issue.number = sister_issues.any? ? sister_issues.sorted_desc.first.number + 1 : 1

          if @issue.save
            redirect_to edit_admin_journal_issue_path(@issue), success: t('.saved')
          else
            flash.now[:alert] = t('.failed')
            render :new, status: :unprocessable_entity
          end
        end

        def update
          if @issue.update(issue_params)
            redirect_to edit_admin_journal_issue_path(@issue), success: t('.saved')
          else
            flash.now[:alert] = t('.failed')
            render :edit, status: :unprocessable_entity
          end
        end

        def destroy
          @issue.destroy
          respond_to do |format|
            format.html do
              redirect_to admin_journal_issues_path, success: t('.deleted')
            end
          end
        end

        def sort
          params[:ids].each.with_index do |id, index|
            Issue.where(id: id).update_all(number: index + 1) # rubocop:disable Rails/SkipsModelValidations
          end
          flash.now[:info] = t('spina.pages.sorting_saved')
          render_flash
        end

        private

        def set_issue
          @issue = Issue.find(params[:id])
        end

        def set_articles
          @articles = @issue.articles.sorted_asc
        end

        def issue_params
          params.require(:issue).permit(PARAMS)
        end

        def set_breadcrumb
          add_breadcrumb Issue.model_name.human(count: :many), admin_journal_issues_path
        end

        def set_tabs
          @tabs = %w[details articles]
        end

        def set_parts_attributes
          @parts_attributes = current_theme.parts.select { |part| PARTS.include? part[:name] }
        end

        def build_parts
          return unless @parts_attributes.is_a? Array

          @parts = @parts_attributes.collect { |part_attributes| @issue.part(part_attributes) }
        end
      end
    end
  end
end

app/views/spina/admin/journal/articles/_form.html.haml
%div{ data: { controller: 'tabs',
              tabs: { active: 'cursor-default text-gray-900 bg-spina-dark bg-opacity-10',
                      inactive: 'cursor-pointer bg-transparent text-gray-400 border-transparent' } } }
  = render Spina::UserInterface::HeaderComponent.new do |header|
    - header.actions do
      - if @article.persisted?
        = render Spina::UserInterface::DropdownComponent.new do |dropdown|
          - dropdown.button(classes: "btn btn-default px-3") do
            = heroicon('dots-horizontal', style: :solid, class: "w-5 h-5 text-gray-600")

          - dropdown.menu do
            = button_to t('spina.permanently_delete'), admin_journal_article_path(@article), method: :delete, class: "block w-full text-left px-4 py-2 text-sm leading-5 font-medium text-red-500 cursor-pointer bg-white hover:bg-red-100 hover:bg-opacity-50 hover:text-red-500 focus:outline-none focus:bg-gray-100 focus:text-gray-900", form: {data: { controller: 'confirm', confirm_message: t('.delete_confirmation', title: @article.title) } }

      = button_tag type: :submit, form: dom_id(@article), class: 'btn btn-primary', data: { controller: 'button', action: 'button#loading', loading_message: t('spina.ui.saving')} do
        = heroicon('check', style: :solid, class: 'w-5 h-5 mr-1 -ml-2')
        = t '.save'

    - header.navigation do
      %nav.-mb-3.mt-4
        %ul.inline-flex.w-auto.rounded-md.bg-white
          - @tabs.each do |tab|
            %button.block.px-3.leading-relaxed.py-1.hover:text-gray-800.rounded-md.text-gray-400.font-medium.text-sm.flex.items-center.whitespace-nowrap{ type: 'button', data: { action: 'tabs#show', 'tabs-target': 'button', 'pane-id': "#{tab}" } }
              = t ".#{tab}"

  .p-4.md:p-8
    - @tabs.each_with_index do |tab, i|
      %div{ 'data-tabs-target': 'pane', id: tab, hidden: i != 0 }
        .max-w-5xl= render "form_#{tab}"

app/views/spina/admin/journal/articles/_form_authors.html.haml
- if @article.persisted?
  .-mt-4.md:-mt-8
    %turbo-frame#article_authors{ src: spina.view_authors_admin_journal_article_path(@article), loading: 'lazy', target: '_top' }

app/views/spina/admin/journal/articles/_form_details.html.haml
= form_with model: [spina, :admin_journal, @article], id: dom_id(@article), html: { autocomplete: 'off' } do |f|
  .-mt-6
  = render Spina::Admin::Journal::FormGroupComponent.new(label: Spina::Admin::Journal::Issue.model_name.human(count: :one)) do
    = f.collection_select(:issue_id,
                          ::Spina::Admin::Journal::Issue.sorted_desc,
                          :id,
                          ->(issue) { t '.volume_issue', volume_number: issue.volume.number, issue_number: issue.number },
                          {},
                          class: 'form-select')
  = render Spina::Admin::Journal::FormGroupComponent.new(label: Spina::Admin::Journal::Article.human_attribute_name(:number),
                                                         description: t('.unchangeable')) do
    = f.number_field :number, disabled: true, class: 'form-input'
  = render Spina::Admin::Journal::FormGroupComponent.new(label: Spina::Admin::Journal::Article.human_attribute_name(:title)) do
    = render Spina::Forms::TextFieldComponent.new(f, :title)
  = render Spina::Admin::Journal::FormGroupComponent.new(label: Spina::Admin::Journal::Article.human_attribute_name(:status)) do
    = f.select :status, Spina::Admin::Journal::Article.statuses.keys.map { |key| [key.humanize, key] }, {}, class: 'form-select'
  = render Spina::Admin::Journal::FormGroupComponent.new(label: Spina::Admin::Journal::Article.human_attribute_name(:licence)) do
    = f.collection_select :licence_id, Spina::Admin::Journal::Licence.sorted, :id, :name, { prompt: true }, { class: 'form-select' }
  = render Spina::Admin::Journal::FormGroupComponent.new(label: Spina::Admin::Journal::Author.model_name.human(count: :many),
                                                         description: t('.affiliation_info')) do
    %ul.list-none.ml-4
      = f.collection_check_boxes(:affiliation_ids,
                                 Spina::Admin::Journal::Affiliation.sorted,
                                 :id,
                                 ->(affiliation) { t '.name_institution', name: affiliation.name, institution: affiliation.institution.name },
                                 {},
                                 class: 'form-checkbox rounded') do |builder|
        %li
          .form-checkbox
            = builder.check_box
            %span.text-sm.font-medium.text-gray-600= builder.label
  = render Spina::Admin::Journal::FormGroupComponent.new(label: Spina::Admin::Journal::Article.human_attribute_name(:url)) do
    = render Spina::Forms::TextFieldComponent.new(f, :url)
  = render Spina::Admin::Journal::FormGroupComponent.new(label: Spina::Admin::Journal::Article.human_attribute_name(:doi)) do
    = render Spina::Forms::TextFieldComponent.new(f, :doi)

  = f.fields_for :"#{@locale}_content", @parts do |ff|
    = ff.hidden_field :type, value: ff.object.class
    = ff.hidden_field :title
    = ff.hidden_field :name

    = render "spina/admin/parts/#{parts_partial_namespace(ff.object.class.to_s)}/form", f: ff

app/views/spina/admin/journal/articles/index.html.haml
= render Spina::UserInterface::HeaderComponent.new do |header|
  - header.actions do
    .ml-3
      = link_to new_admin_journal_article_path, class: 'btn btn-primary w-full' do
        = heroicon 'plus', style: :solid, class: 'w-7 h-7 -m1-2'
        = t '.new'

=  render Spina::Admin::Journal::ArticlesListComponent.new(articles: @articles)

app/views/spina/admin/journal/articles/view_authors.html.haml
%turbo-frame#article_authors
  = render Spina::Admin::Journal::AuthorshipsListComponent.new(authorships: @article.authorships.sorted_within_article, sortable: true)